### ISSUE TITLE
Design doc review #3 - Backend and Frontend routes

### ISSUE THREAD

**Issue by aracpyon** [Junghyun2006/Amica#3]
**Backend routes**
- [x] Update your backend routes based on the changes made to your schema
* How do I set up backend routing for relational data?
1. Return all channels for a specific server
    - `server` has many channels so you can get the channel's information easily on your jbuilder by doing `server.channels`
2. Return all subscriptions for a specific server
    - each server has many subscriptions and many members through subscriptions. You can send the information through association on the jbuilder to the frontend.
3. Return all channel messages for a specific channel
    - similar as above. You can use associations. 
4. Return all direct messages for a specific conversation between two users
    - There will be a `conversation` table and messages will belong to a certain conversation. You can use association again. 

**Frontend routes**
- [x] `/servers/:server_id` You need `channelList` component here
- [x] `/servers/settings` => this is the edit page for server right?
- [x] `/servers/discovery` => what is this for?
- [x] `/servers/:server_id/:channel_id` => change this to `/servers/:server_id/channels/:channel_id`
- [x] `/servers/:server_id/:channel_id/:channel_message_id` You don't need this route because messages will show up on the channel's showpage(`/servers/:server_id/channels/:channel_id`)
- [x] `/@me/direct_message:id` => `/@me/:conversationId`

**Comment by Junghyun2006** [comment]
/servers/settings => this is the edit page for server right?

- Yes, but now I have modified all the edits to be done through a modal.

/servers/discovery => what is this for? 

- This is to browse and explore other servers 
- the route has been modified to `/discovery`

**Comment by aracpyon** [comment]
Sorry, I think when you talked about `relational backend data`, I guess you were talking about this: 

- [x] Make another `GET` route for `channels`: `GET /api/servers/:id/channels` because you need to return all the channels that belong to one server. 
- [x] Make another `GET` route for `messages`: `GET /api/channels/:channel_id/messages` to get the messages that belongs to a specific messages
- [x] Make `GET` route for `messages: `GET /api/conversations/:conversation_id/messages` to get the messages that belong to a specific conversation

Yes, not only the jbuilder, you also need to set up these backend routes

**Comment by Junghyun2006** [comment]
Thanks Ara! That makes a lot of sense.
